const Router = require('express')
const router = new Router()
const dispensingBlockController = require('../controller/dispensingBlock.controller')
const drugNameController = require('../controller/drugNameController')
const imgController = require('../controller/imgTest')
const localityController = require('../controller/localityController')
const tareController = require('../controller/tare.controller')

router.post('/locality', localityController.getLocality)
router.post('/drugsName', drugNameController.getDrugName)
router.post('/dispensing', dispensingBlockController.createDispensing)
router.post('/organizations', tareController.getOrganization)
router.post('/tare', tareController.getTare)
router.post('/tar', tareController.getTar)
router.post('/tare-accepting', tareController.tareAccepting)
// router.post('/dispensing', dispensingBlockController.createTest)
router.get('/test', dispensingBlockController.getAllTests)
router.post('/img', dispensingBlockController.getImg)
router.get('/testPhoto', imgController.test)
// router.get('/user', dispensingBlockController.getUsers)
// router.get('/user', dispensingBlockController.getUsers)
// router.get('/user/:id', dispensingBlockController.getOneUser)
// router.put('/user/:id', dispensingBlockController.updateUser)
// router.delete('/user/:id', dispensingBlockController.deleteUser)

module.exports = router